name: 'vpro maven build'
description: 'checking out, setting up .m2, gpg'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Clean settings.xml
      run: rm -rf ~/.m2/settings.xml
    - name: Create settings.xml
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}, {"id": "gpg.passphrase", "passphrase": "${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"}]'
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'github $GITHUB_ACTOR'
        email: 'digitaal-techniek@vpro.nl'
        token: '${{ secrets.GITHUB_TOKEN  }}'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
